version: '3.8'

services:
  zebra:
    image: zfnd/zebra:latest
    container_name: zebra
    restart: always
    ports:
      - "${ZEBRA_RPC_PORT:-8232}:8232"     # RPC port for API access (same as zcashd for compatibility)
      - "${ZEBRA_P2P_PORT:-8233}:8233"     # P2P port for peer connections
    volumes:
      - ${DATA_DIR}/zebrad-cache:/var/cache/zebrad-cache
      - ./zebrad.toml:/etc/zebrad/zebrad.toml:ro
    networks:
      - zcash-network

networks:
  zcash-network:
    external: true
    name: zcash-network
