services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${NGINX_CONFIG_PATH:-./nginx.conf}:/etc/nginx/nginx.conf:ro
      - ${DATA_DIR}/nginx_logs:/var/log/nginx
    networks:
      - zcash-network

networks:
  zcash-network:
    external: true
